name: "Protocol Buffer Go Stubs Generation"
on:
  push:
    tags:
      - v**

permissions: write-all

jobs:
  protoc:
    name: "Generate"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ["job"]
    steps:

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22
      - uses: actions/checkout@v3

      - name: Etract Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: "Generate for Golang"
        shell: bash
        run: |
          ls
          chmod +x "${GITHUB_WORKSPACE}/bin/autogen.sh"
          ./bin/autogen.sh ${{ matrix.service }} ${{ env.RELEASE_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
